version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  container1:
    build: 
      context: ./container1
      dockerfile: Dockerfile
  